namespace Stratum.Common.Infrastructure.BugCapture;

public enum UserActionType
{
    Unknown,
    Navigation,
    MenuClick,
    ButtonClick,
    LinkClick,
    FormSave,
    FormCancel,
    FormReset,
    FieldChange,
    FieldFocus,
    FieldBlur,
    GridAction,
    GridSort,
    GridFilter,
    GridPageChange,
    GridRowSelect,
    GridRowExpand,
    TabChange,
    ModalOpen,
    ModalClose,
    ModalConfirm,
    ModalCancel,
    FileUpload,
    FileDownload,
    ApiRequest,
    ApiResponse,
    ApiError,
    Notification,
    ThemeChange,
    LanguageChange,
    LogOut,
    SessionStart,
    Error,
}
