namespace Stratum.Common.UI.Services;

using System.Collections.Concurrent;

/// <summary>
/// Scoped service that tracks virtual circuit IDs (generated by <c>EntityPresenceLayout</c>)
/// within the current Blazor circuit. Used by <see cref="CircuitPresenceHandler"/> to
/// clean up presence entries when the circuit disconnects.
/// </summary>
internal sealed class CircuitPresenceRegistry
{
    private readonly ConcurrentDictionary<string, byte> _circuitIds = new(StringComparer.Ordinal);

    /// <summary>Register a virtual circuit ID for cleanup on disconnect.</summary>
    public void Register(string virtualCircuitId) => _circuitIds.TryAdd(virtualCircuitId, 0);

    /// <summary>Unregister a virtual circuit ID (e.g. on navigation away).</summary>
    public void Unregister(string virtualCircuitId) => _circuitIds.TryRemove(virtualCircuitId, out _);

    /// <summary>Get all currently registered virtual circuit IDs.</summary>
    public IReadOnlyList<string> GetAll() => [.. _circuitIds.Keys];
}
