namespace Stratum.Common.Infrastructure.Tests.Unit.BugCapture;

using System.Net;
using System.Text.Json;
using FluentAssertions;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using Stratum.Common.Infrastructure.BugCapture;
using Xunit;

public sealed class GitHubIssueReporterTests
{
    private static readonly CaptureBundle SampleBugBundle = CreateBundle(CaptureType.Bug, "Login page crashes on submit");
    private static readonly CaptureBundle SampleFeatureBundle = CreateBundle(CaptureType.Feature, "Add dark mode toggle");

    [Fact]
    public void BuildTitle_Should_Use_Bug_Prefix_For_Bug_Type()
    {
        var title = GitHubIssueReporter.BuildTitle(SampleBugBundle);

        title.Should().StartWith("[Bug]");
        title.Should().Contain("Login page crashes on submit");
    }

    [Fact]
    public void BuildTitle_Should_Use_Feature_Prefix_For_Feature_Type()
    {
        var title = GitHubIssueReporter.BuildTitle(SampleFeatureBundle);

        title.Should().StartWith("[Feature]");
        title.Should().Contain("Add dark mode toggle");
    }

    [Fact]
    public void BuildTitle_Should_Truncate_Long_Comments()
    {
        var longComment = new string('x', 200);
        var bundle = CreateBundle(CaptureType.Bug, longComment);

        var title = GitHubIssueReporter.BuildTitle(bundle);

        title.Length.Should().BeLessThanOrEqualTo(90); // "[Bug] " + 80 chars max + "..."
        title.Should().EndWith("...");
    }

    [Fact]
    public void BuildTitle_Should_Use_Capture_Id_When_No_Comments()
    {
        var bundle = CreateBundle(CaptureType.Bug, comments: []);

        var title = GitHubIssueReporter.BuildTitle(bundle);

        title.Should().StartWith("[Bug] Capture ");
    }

    [Fact]
    public void BuildBody_Should_Include_Description_Section()
    {
        var body = GitHubIssueReporter.BuildBody(SampleBugBundle);

        body.Should().Contain("## Description");
        body.Should().Contain("Login page crashes on submit");
    }

    [Fact]
    public void BuildBody_Should_Include_Tags_Section()
    {
        var bundle = CreateBundle(CaptureType.Bug, "test", tags: ["ui", "critical"]);

        var body = GitHubIssueReporter.BuildBody(bundle);

        body.Should().Contain("## Tags");
        body.Should().Contain("`ui`");
        body.Should().Contain("`critical`");
    }

    [Fact]
    public void BuildBody_Should_Include_Environment_Table()
    {
        var body = GitHubIssueReporter.BuildBody(SampleBugBundle);

        body.Should().Contain("## Environment");
        body.Should().Contain("| Project | Stratum |");
        body.Should().Contain("| OS |");
    }

    [Fact]
    public void BuildBody_Should_Include_User_Actions_In_Details()
    {
        var bundle = CreateBundle(CaptureType.Bug, "test", userActions:
        [
            new UserActionEntry
            {
                ActionType = UserActionType.ButtonClick,
                Description = "Clicked submit button",
                Timestamp = DateTimeOffset.UtcNow,
            },
        ]);

        var body = GitHubIssueReporter.BuildBody(bundle);

        body.Should().Contain("## User Actions");
        body.Should().Contain("<details>");
        body.Should().Contain("Clicked submit button");
    }

    [Fact]
    public void BuildBody_Should_Include_Logs_In_Details()
    {
        var bundle = CreateBundle(CaptureType.Bug, "test", logs:
        [
            new LogEntry
            {
                Timestamp = DateTimeOffset.UtcNow,
                Level = "Error",
                Category = "App",
                Message = "NullReferenceException in Handler",
            },
        ]);

        var body = GitHubIssueReporter.BuildBody(bundle);

        body.Should().Contain("## Application Logs");
        body.Should().Contain("<details>");
        body.Should().Contain("NullReferenceException in Handler");
    }

    [Fact]
    public void BuildBody_Should_Include_Http_Traffic_In_Details()
    {
        var bundle = CreateBundle(CaptureType.Bug, "test", httpTraffic:
        [
            new HttpTrafficRecord
            {
                Method = "POST",
                Url = "/api/v1/login",
                StatusCode = 500,
                DurationMs = 234,
                Timestamp = DateTimeOffset.UtcNow,
                IsError = true,
            },
        ]);

        var body = GitHubIssueReporter.BuildBody(bundle);

        body.Should().Contain("## HTTP Traffic");
        body.Should().Contain("<details>");
        body.Should().Contain("/api/v1/login");
    }

    [Fact]
    public void BuildBody_Should_Include_Generated_Footer()
    {
        var body = GitHubIssueReporter.BuildBody(SampleBugBundle);

        body.Should().Contain("_Generated by Stratum BugCapture_");
    }

    [Fact]
    public void BuildLabels_Should_Include_Default_Labels_And_Bug()
    {
        var config = new GitHubIssueConfiguration { DefaultLabels = ["bug-capture"] };

        var labels = GitHubIssueReporter.BuildLabels(SampleBugBundle, config);

        labels.Should().Contain("bug-capture");
        labels.Should().Contain("bug");
        labels.Should().NotContain("enhancement");
    }

    [Fact]
    public void BuildLabels_Should_Include_Enhancement_For_Feature()
    {
        var config = new GitHubIssueConfiguration { DefaultLabels = ["bug-capture"] };

        var labels = GitHubIssueReporter.BuildLabels(SampleFeatureBundle, config);

        labels.Should().Contain("bug-capture");
        labels.Should().Contain("enhancement");
        labels.Should().NotContain("bug");
    }

    [Fact]
    public async Task ReportAsync_Should_Fallback_When_Config_Missing()
    {
        var fallback = new FakeBundleReporter();
        var reporter = CreateReporter(
            config: new CaptureConfiguration { GitHub = null },
            fallback: fallback);

        var result = await reporter.ReportAsync(SampleBugBundle);

        result.Should().Be("local://fallback");
        fallback.CallCount.Should().Be(1);
    }

    [Fact]
    public async Task ReportAsync_Should_Fallback_When_Token_Empty()
    {
        var fallback = new FakeBundleReporter();
        var reporter = CreateReporter(
            config: new CaptureConfiguration
            {
                GitHub = new GitHubIssueConfiguration { Owner = "org", Repo = "repo", Token = string.Empty },
            },
            fallback: fallback);

        var result = await reporter.ReportAsync(SampleBugBundle);

        result.Should().Be("local://fallback");
        fallback.CallCount.Should().Be(1);
    }

    [Fact]
    public async Task ReportAsync_Should_Fallback_On_Http_Error()
    {
        var fallback = new FakeBundleReporter();
        var handler = new FakeHttpHandler(HttpStatusCode.InternalServerError, "{}");
        var reporter = CreateReporter(
            config: CreateValidConfig(),
            fallback: fallback,
            handler: handler);

        var result = await reporter.ReportAsync(SampleBugBundle);

        result.Should().Be("local://fallback");
        fallback.CallCount.Should().Be(1);
    }

    [Fact]
    public async Task ReportAsync_Should_Return_Issue_Url_On_Success()
    {
        var issueUrl = "https://github.com/org/repo/issues/42";
        var responseBody = JsonSerializer.Serialize(new { html_url = issueUrl });
        var handler = new FakeHttpHandler(HttpStatusCode.Created, responseBody);
        var fallback = new FakeBundleReporter();
        var reporter = CreateReporter(
            config: CreateValidConfig(),
            fallback: fallback,
            handler: handler);

        var result = await reporter.ReportAsync(SampleBugBundle);

        result.Should().Be(issueUrl);
        fallback.CallCount.Should().Be(0);
    }

    [Fact]
    public async Task ReportAsync_Should_Send_Correct_Request()
    {
        var responseBody = JsonSerializer.Serialize(new { html_url = "https://github.com/org/repo/issues/1" });
        var handler = new FakeHttpHandler(HttpStatusCode.Created, responseBody);
        var reporter = CreateReporter(
            config: CreateValidConfig(),
            fallback: new FakeBundleReporter(),
            handler: handler);

        await reporter.ReportAsync(SampleBugBundle);

        handler.LastRequestUri.Should().Contain("/repos/test-owner/test-repo/issues");
        handler.LastRequestBody.Should().Contain("[Bug]");
        handler.LastRequestBody.Should().Contain("Login page crashes on submit");
    }

    [Fact]
    public async Task ReportAsync_Should_Fallback_When_Response_Missing_HtmlUrl()
    {
        var handler = new FakeHttpHandler(HttpStatusCode.Created, "{}");
        var fallback = new FakeBundleReporter();
        var reporter = CreateReporter(
            config: CreateValidConfig(),
            fallback: fallback,
            handler: handler);

        var result = await reporter.ReportAsync(SampleBugBundle);

        result.Should().Be("local://fallback");
        fallback.CallCount.Should().Be(1);
    }

    [Fact]
    public void BuildBody_Should_Include_Screenshot_Metadata()
    {
        var bundle = CreateBundle(CaptureType.Bug, "test", medias:
        [
            new MediaCapture
            {
                Id = Guid.NewGuid(),
                MediaType = "screenshot",
                FilePath = "/nonexistent/path.png",
                FileName = "screenshot.png",
                MimeType = "image/png",
                FileSizeBytes = 12345,
                CapturedAt = DateTimeOffset.UtcNow,
                Description = "Login page",
                Sequence = 0,
            },
        ]);

        var body = GitHubIssueReporter.BuildBody(bundle);

        body.Should().Contain("## Screenshots");
        body.Should().Contain("**Login page**");
        body.Should().Contain("12,345 bytes");
    }

    private static CaptureConfiguration CreateValidConfig() => new()
    {
        GitHub = new GitHubIssueConfiguration
        {
            Owner = "test-owner",
            Repo = "test-repo",
            Token = "ghp_test_token_12345",
        },
    };

    private static GitHubIssueReporter CreateReporter(
        CaptureConfiguration config,
        FakeBundleReporter fallback,
        FakeHttpHandler? handler = null)
    {
        handler ??= new FakeHttpHandler(HttpStatusCode.InternalServerError, "{}");
        var factory = new FakeHttpClientFactory(handler);
        return new GitHubIssueReporter(
            factory,
            (IBundleReporter)fallback,
            Options.Create(config),
            NullLogger<GitHubIssueReporter>.Instance);
    }

    private static CaptureBundle CreateBundle(
        CaptureType type,
        string? comment = null,
        IReadOnlyList<string>? comments = null,
        IReadOnlyList<string>? tags = null,
        IReadOnlyList<UserActionEntry>? userActions = null,
        IReadOnlyList<LogEntry>? logs = null,
        IReadOnlyList<HttpTrafficRecord>? httpTraffic = null,
        IReadOnlyList<MediaCapture>? medias = null)
    {
        return new CaptureBundle
        {
            Id = Guid.NewGuid(),
            Type = type,
            Metadata = new CaptureMetadata
            {
                Project = "Stratum",
                StartedAt = DateTimeOffset.UtcNow.AddMinutes(-5),
                FinishedAt = DateTimeOffset.UtcNow,
                Os = "Windows 11",
                User = "testuser",
                ScreenResolution = "1920x1080",
                DotNetVersion = "9.0.0",
            },
            Medias = medias ?? [],
            Logs = logs ?? [],
            HttpTraffic = httpTraffic ?? [],
            UserActions = userActions ?? [],
            Comments = comments ?? (comment is not null ? [comment] : []),
            Tags = tags ?? [],
        };
    }

    private sealed class FakeHttpClientFactory : IHttpClientFactory
    {
        private readonly HttpMessageHandler _handler;

        public FakeHttpClientFactory(HttpMessageHandler handler)
        {
            _handler = handler;
        }

        public HttpClient CreateClient(string name) => new(_handler, disposeHandler: false)
        {
            BaseAddress = new Uri("https://api.github.com"),
        };
    }

    private sealed class FakeBundleReporter : IBundleReporter
    {
        public int CallCount { get; private set; }

        public Task<string> ReportAsync(CaptureBundle bundle)
        {
            CallCount++;
            return Task.FromResult("local://fallback");
        }
    }

    private sealed class FakeHttpHandler : HttpMessageHandler
    {
        private readonly HttpStatusCode _statusCode;
        private readonly string _responseBody;

        public FakeHttpHandler(HttpStatusCode statusCode, string responseBody)
        {
            _statusCode = statusCode;
            _responseBody = responseBody;
        }

        public string? LastRequestUri { get; private set; }

        public string? LastRequestBody { get; private set; }

        protected override async Task<HttpResponseMessage> SendAsync(
            HttpRequestMessage request, CancellationToken cancellationToken)
        {
            LastRequestUri = request.RequestUri?.ToString();
            if (request.Content is not null)
            {
                LastRequestBody = await request.Content.ReadAsStringAsync(cancellationToken);
            }

            return new HttpResponseMessage(_statusCode)
            {
                Content = new StringContent(_responseBody, System.Text.Encoding.UTF8, "application/json"),
            };
        }
    }
}
